In [36]:
import pickle
import numpy as np
import pandas as pd


In [37]:
##These lines are used to load back your saved machine learning objects from .pkl files.

#You already saved them using pickle.dump().
#Now pickle.load() restores them so you can use them again without retraining.
#What 'rb' means   
#r → read mode
#b → binary mode
#With pickle:
#you directly load the trained model in seconds
#Pickle files are binary files.

ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [38]:
# Assume user input
#pclass/gender/age/sibsp/parch/fare/embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [39]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [40]:
test_input_sex

array([[0., 1.]])

In [41]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [42]:
test_input_embarked 

array([[0., 0., 1.]])

In [43]:
test_input_age = test_input[:,2].reshape(1,1)

In [44]:
np.concatenate(
    (
        test_input[:,[0,3,4,5]],
        test_input_age,
        test_input_sex,
        test_input_embarked
    ),
    axis=1
)

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [45]:
test_input_transformed.shape

(1, 10)

In [46]:
clf.predict(test_input_transformed)

array([1])